---

- name: enumerate IP addresses (but not the loopback interface)
  shell: ip -f inet addr show | grep -Po 'inet \K(?(?=127.0.0.1)|[\d.]+)'
  register: ip_addrs


- name: copy openssl conf file for server {{ cert_common_name }}
  template:
    src: "server.conf.j2"
    dest: "{{ pki_root_path }}/etc/server_{{ cert_common_name }}.conf"
    mode: 0640
  delegate_to: localhost

### key
- name: check if {{ cert_common_name }} key file exists
  stat:
    path: "{{ pki_root_path }}/certs/{{ cert_common_name }}.key"
  delegate_to: localhost
  register: server_key_present

- name: create {{ cert_common_name }} key file
  command: "openssl genrsa -out {{ pki_root_path }}/certs/{{ cert_common_name }}.key {{ ca_rsa_key_size }}"
  args:
    chdir: "{{ pki_root_path }}"
  delegate_to: localhost
  when: server_key_present.stat.exists != True

- name: set mode for {{ cert_common_name }} key file
  file:
    path: "{{ pki_root_path }}/certs/{{ cert_common_name }}.key"
    mode: 0400
  delegate_to: localhost

### cert request
- name: check if {{ cert_common_name }} CSR file exists
  stat:
    path: "{{ pki_root_path }}/certs/{{ cert_common_name }}.csr"
  delegate_to: localhost
  register: cert_csr_present

- name: create request for {{ cert_common_name }} cert
  shell: |
    openssl req -new \
      -key {{ pki_root_path }}/certs/{{ cert_common_name }}.key \
      -out {{ pki_root_path }}/certs/{{ cert_common_name }}.csr \
      -subj "/C={{ca_country}}/ST={{ca_state}}/L={{ca_locality}}/O={{ca_organization_name}}/OU={{ca_organizational_unit}}/CN={{cert_common_name}}" \
      -config {{ pki_root_path }}/etc/server_{{ cert_common_name }}.conf
  args:
    executable: /bin/bash
    chdir: "{{ pki_root_path }}"
  delegate_to: localhost
  when: cert_csr_present.stat.exists == False

- name: set mode for {{ cert_common_name }} csr file
  file:
    path: "{{ pki_root_path }}/certs/{{ cert_common_name }}.csr"
    mode: 0640
  delegate_to: localhost

### cert issue
- name: check if {{ cert_common_name }} certificate file exists
  stat:
    path: "{{ pki_root_path }}/certs/{{ cert_common_name }}.crt"
  delegate_to: localhost
  register: cert_crt_present

- name: Generate {{ cert_common_name }} certificate
  shell: |
    openssl ca -batch \
      -config {{ pki_root_path }}/etc/signing-ca.conf \
      -in {{ pki_root_path }}/certs/{{ cert_common_name }}.csr \
      -out {{ pki_root_path }}/certs/{{ cert_common_name }}.crt \
      -extensions server_ext
  args:
    executable: /bin/bash
    chdir: "{{ pki_root_path }}"
  delegate_to: localhost
  when: cert_crt_present.stat.exists == False

- name: set mode for{{ cert_common_name }} crt file
  file:
    path: "{{ pki_root_path }}/certs/{{ cert_common_name }}.crt"
    mode: 0640
  delegate_to: localhost

# vim: bs=2 sw=2 expandtab: